### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EdwardCaf**
Links in ReadMe resolve with 404 error. Updated link urls

### CODE REVIEW

**Comment by Favorlock** [comment]
Resolves #36

**Comment by ShalokShalom** [comment]
How does it help, that this is in development now?
Links are still broken

**Comment by Favorlock** [comment]
All work (except critical bug fixes) take place on the development branch. The updates to the readme will be included when we release a new version.

**Comment by ShalokShalom** [comment]
oO

**Pull request merged**
